site_name: BCU Dungeon World
site_url: https://hetyey-b.github.io/bcu_dungeon_world/
theme:
  name: material
  palette:
    scheme:
      slate
nav:
  - 'Home': 'index.md'
  - 'Moves':
    - 'General': 'Moves.md'
    - 'Basic moves': 'Moves/Basic moves.md'
    - 'Journey moves': 'Moves/Journey moves.md'
    - 'Special moves': 'Moves/Special moves.md'
  - 'Character creation': 'Character creation.md'
  - 'Character species': 'Character species.md'
  - 'Bonds and Alignment': 'Bonds and Alignment.md'
  - 'HP and Damage': 'HP and Damage.md'
  - 'Character playbooks':
    - 'General': 'Character playbooks/General.md'
    - 'The Barbarian': 'Character playbooks/The Barbarian.md'
    - 'The Bard': 'Character playbooks/The Bard.md'
    - 'The Battlemaster': 'Character playbooks/The Battlemaster.md'
    - 'The Chaneller': 'Character playbooks/The Chaneller.md'
    - 'The Cleric': 'Character playbooks/The Cleric.md'
    - 'The Druid': 'Character playbooks/The Druid.md'
    - 'The Fighter': 'Character playbooks/The Fighter.md'
    - 'The Necromancer': 'Character playbooks/The Necromancer.md'
    - 'The Paladin': 'Character playbooks/The Paladin.md'
    - 'The Ranger': 'Character playbooks/The Ranger.md'
    - 'The Shaman': 'Character playbooks/The Shaman.md'
    - 'The Skirmisher': 'Character playbooks/The Skirmisher.md'
    - 'The Templar': 'Character playbooks/The Templar.md'
    - 'The Thief': 'Character playbooks/The Thief.md'
    - 'The Wizard': 'Character playbooks/The Wizard.md'
    - 'Compendium Playbooks':
      - 'The Delver': 'Character playbooks/Compendium playbooks/The Delver.md'
      - 'The Drunken Master': 'Character playbooks/Compendium playbooks/The Drunken Master.md'
      - 'The Explorer': 'Character playbooks/Compendium playbooks/The Explorer.md'
      - 'The Hunter': 'Character playbooks/Compendium playbooks/The Hunter.md'
      - 'The Knight of the Forever Flame': 'Character playbooks/Compendium playbooks/The Knight of the Forever Flame.md'
      - 'The Walker in the Waste': 'Character playbooks/Compendium playbooks/The Walker in the Waste.md'
      - 'The Wendigo': 'Character playbooks/Compendium playbooks/The Wendigo.md'
  - 'Equipment':  'Equipment.md'
  - 'Followers':
    - 'General': 'Followers/General.md'
    - 'Follower moves': 'Followers/Follower moves.md'
  - 'FAQ': 'FAQ.md'
